### ISSUE TITLE
update to 3.1.4

### ISSUE THREAD

**Issue by vukomir** [macexx/EAP-Controller#7]
hi,

after update to the last version, MongoDB is not starting, this is the error that i get in the logs

`2019-04-16 22:20:17 [main] [INFO]-[SourceFile:85] - going to start mongod.
2019-04-16 22:21:58 [main] [WARN]-[SourceFile:124] - Fail to start mongo DB server
2019-04-16 22:21:58 [main] [WARN]-[SourceFile:78] - com.tp_link.eap.start.a.a: Fail to start mongo DB server
com.tp_link.eap.start.a.a: Fail to start mongo DB server
        at com.tp_link.eap.start.c.c.a(SourceFile:125) ~[eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.c.a.e(SourceFile:75) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.a.g(SourceFile:310) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.a.z(SourceFile:389) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.a.a(SourceFile:86) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.a.h(SourceFile:336) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.EapLinuxMain.b(SourceFile:79) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.EapLinuxMain.start(SourceFile:36) [eap-start-3.1.4.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
        at org.apache.commons.daemon.support.DaemonLoader.start(DaemonLoader.java:243) [commons-daemon-1.0.15.jar:1.0.15]
2019-04-16 22:22:00 [main] [INFO]-[SourceFile:168] - mongod is not running
2019-04-16 22:23:40 [main] [WARN]-[SourceFile:124] - Fail to start mongo DB server
2019-04-16 22:23:40 [main] [WARN]-[SourceFile:78] - com.tp_link.eap.start.a.a: Fail to start mongo DB server
com.tp_link.eap.start.a.a: Fail to start mongo DB server
        at com.tp_link.eap.start.c.c.a(SourceFile:125) ~[eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.c.a.e(SourceFile:75) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.a.g(SourceFile:310) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.a.w(SourceFile:303) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.a.z(SourceFile:392) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.a.a(SourceFile:86) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.a.h(SourceFile:336) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.EapLinuxMain.b(SourceFile:79) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.EapLinuxMain.start(SourceFile:36) [eap-start-3.1.4.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
        at org.apache.commons.daemon.support.DaemonLoader.start(DaemonLoader.java:243) [commons-daemon-1.0.15.jar:1.0.15]
2019-04-16 22:23:43 [main] [INFO]-[ContextHandler.java:2040] - Initializing Spring root WebApplicationContext
2019-04-16 22:23:43 [pool-5-thread-1] [INFO]-[SourceFile:91] - Omada Controller isn't prepared to handle event
2019-04-16 22:23:44 [pool-5-thread-2] [INFO]-[SourceFile:91] - Omada Controller isn't prepared to handle event
2019-04-16 22:23:48 [pool-5-thread-3] [INFO]-[SourceFile:91] - Omada Controller isn't prepared to handle event
2019-04-16 22:23:49 [pool-5-thread-1] [INFO]-[SourceFile:91] - Omada Controller isn't prepared to handle event
2019-04-16 22:23:51 [Thread-3] [INFO]-[SourceFile:168] - mongod is not running
2019-04-16 22:23:51 [Thread-3] [INFO]-[SourceFile:474] - mongod was shutdown , restarting it
2019-04-16 22:23:53 [pool-5-thread-2] [INFO]-[SourceFile:91] - Omada Controller isn't prepared to handle event
2019-04-16 22:23:54 [pool-5-thread-3] [INFO]-[SourceFile:91] - Omada Controller isn't prepared to handle event
2019-04-16 22:23:57 [main] [ERROR]-[ContextLoader.java:331] - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'siteRepository': Invocation of init method failed; nested exception is com.mongodb.MongoTimeoutException: Timed out while waiting for a server that matches AnyServerSelector{} after 3932 ms
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1553) ~[spring-beans-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539) ~[spring-beans-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475) ~[spring-beans-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304) ~[spring-beans-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300) ~[spring-beans-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195) ~[spring-beans-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:684) ~[spring-beans-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760) ~[spring-context-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482) ~[spring-context-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403) ~[spring-web-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306) [spring-web-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106) [spring-web-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:782) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:424) [jetty-servlet-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:774) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249) [jetty-servlet-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242) [jetty-webapp-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494) [jetty-webapp-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:774) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249) [jetty-servlet-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242) [jetty-webapp-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494) [jetty-webapp-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:172) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.server.Server.doStart(Server.java:282) [jetty-server-8.1.15.v20140411.jar:8.1.15.v20140411]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.15.v20140411.jar:8.1.15.v20140411]
        at com.tp_link.eap.start.c.b.a(SourceFile:40) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.c.a.e(SourceFile:75) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.task.EapJettyStartUpTask.a(SourceFile:19) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.m.e.a(SourceFile:13) [eap-infrastructure-3.1.4.jar:?]
        at com.tp_link.eap.start.a.i(SourceFile:425) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.EapLinuxMain.b(SourceFile:86) [eap-start-3.1.4.jar:?]
        at com.tp_link.eap.start.EapLinuxMain.start(SourceFile:36) [eap-start-3.1.4.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
        at org.apache.commons.daemon.support.DaemonLoader.start(DaemonLoader.java:243) [commons-daemon-1.0.15.jar:1.0.15]
Caused by: com.mongodb.MongoTimeoutException: Timed out while waiting for a server that matches AnyServerSelector{} after 3932 ms
        at com.mongodb.BaseCluster.getServer(BaseCluster.java:87) ~[mongo-java-driver-2.12.2.jar:?]
        at com.mongodb.DBTCPConnector.getServer(DBTCPConnector.java:654) ~[mongo-java-driver-2.12.2.jar:?]
        at com.mongodb.DBTCPConnector.access$300(DBTCPConnector.java:39) ~[mongo-java-driver-2.12.2.jar:?]
        at com.mongodb.DBTCPConnector$MyPort.getConnection(DBTCPConnector.java:503) ~[mongo-java-driver-2.12.2.jar:?]
        at com.mongodb.DBTCPConnector$MyPort.get(DBTCPConnector.java:451) ~[mongo-java-driver-2.12.2.jar:?]
        at com.mongodb.DBTCPConnector.getPrimaryPort(DBTCPConnector.java:409) ~[mongo-java-driver-2.12.2.jar:?]
        at com.mongodb.DBCollectionImpl.createIndex(DBCollectionImpl.java:337) ~[mongo-java-driver-2.12.2.jar:?]
        at com.mongodb.DBCollection.createIndex(DBCollection.java:564) ~[mongo-java-driver-2.12.2.jar:?]
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.createIndex(MongoPersistentEntityIndexCreator.java:135) ~[spring-data-mongodb-1.5.1.RELEASE.jar:?]
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForAndCreateIndexes(MongoPersistentEntityIndexCreator.java:129) ~[spring-data-mongodb-1.5.1.RELEASE.jar:?]
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForIndexes(MongoPersistentEntityIndexCreator.java:121) ~[spring-data-mongodb-1.5.1.RELEASE.jar:?]
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.onApplicationEvent(MongoPersistentEntityIndexCreator.java:105) ~[spring-data-mongodb-1.5.1.RELEASE.jar:?]
        at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.onApplicationEvent(MongoPersistentEntityIndexCreator.java:46) ~[spring-data-mongodb-1.5.1.RELEASE.jar:?]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:98) ~[spring-context-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:333) ~[spring-context-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:307) ~[spring-data-commons-1.8.1.RELEASE.jar:?]
        at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:181) ~[spring-data-commons-1.8.1.RELEASE.jar:?]
        at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:141) ~[spring-data-commons-1.8.1.RELEASE.jar:?]
        at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:67) ~[spring-data-commons-1.8.1.RELEASE.jar:?]
        at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getEntityInformation(MongoRepositoryFactory.java:141) ~[spring-data-mongodb-1.5.1.RELEASE.jar:?]
        at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getTargetRepository(MongoRepositoryFactory.java:83) ~[spring-data-mongodb-1.5.1.RELEASE.jar:?]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:158) ~[spring-data-commons-1.8.1.RELEASE.jar:?]
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:224) ~[spring-data-commons-1.8.1.RELEASE.jar:?]
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:210) ~[spring-data-commons-1.8.1.RELEASE.jar:?]
        at org.springframework.data.mongodb.repository.support.MongoRepositoryFactoryBean.afterPropertiesSet(MongoRepositoryFactoryBean.java:108) ~[spring-data-mongodb-1.5.1.RELEASE.jar:?]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1612) ~[spring-beans-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1549) ~[spring-beans-4.0.5.RELEASE.jar:4.0.5.RELEASE]
        ... 38 more
2019-04-16 22:23:57 [main] [ERROR]-[SourceFile:66] - Failed to get WebApplicationContext, EapMetaDataInitTask execute failed!
2019-04-16 22:23:57 [main] [ERROR]-[SourceFile:17] - Failed to start omada controller, going to exit
                                                                                                                                      `

**Comment by vukomir** [comment]
same issue if i try setup a new image, if i use an external volume mongo will not start
